Django_prj/urls.py
#path뒤 include 추가
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),#어드민 사이트 연결해주기 admin을 붙였을때 링크되는 위치
    path('', include('single_pages.urls')), #아무것도 붙이지 않으면 single_pages로(single_pages에 urls파일이 없으므로 생성하기)
    path('blog/', include('blog.urls')),#blog를 붙였을때 연결위치(마찬가지로 blog에도 urls파일 생성해주기)
    path('exam/', include('exam.urls')),
    path('accounts/', include('allauth.urls')),
    path('final4/', include('final4.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
#Django_prj url에서 형식 가져옴
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.PostList.as_view()),#CBV방식의 지정(views에 있는 PostList의 클래스를 보여라 라는뜻)
    #path('', views.index),#FBV방식의 지정
    #CBV방식
    path('<int:pk>/', views.PostDetail.as_view()),
    path('category/<str:slug>/', views.category_page),#문자열을 slug에 담아서
    path('create_post/', views.PostCreate.as_view()), #PostCreate 클래스 참조
    path('update_post/<int:pk>/', views.PostUpdate.as_view()), #postupdate 클래스 참조
    ##댓글 부분
    path('<int:pk>/new_comment/', views.new_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('delete_comment/<int:pk>', views.delete_comment),
    #검색 부분
    path('search/<str:q>/',views.PostSearch.as_view()),
    #FBV방식
    #path('<int:pk>/', views.single_post_page),#모델을 포함시키는 형태로 만들기 위해 single_pages랑 살짝 다름
        #int:pk는 views.single_post_page 여기에 인자값으로 넘김.
]

exam/urls.py
#Django_prj url에서 형식 가져옴
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index),
    path('prob/', views.St_List.as_view()),
    path('prob/<int:pk>/', views.St_Detail.as_view()),
]

exam/models.py
from django.db import models


# Create your models here.
class Student(models.Model):  # 일종의 db구조 , field설정
    num = models.CharField(max_length=15)
    name = models.CharField(max_length=30)
    birth = models.DateField()
    Depart = models.CharField(max_length=100)

    image = models.ImageField(upload_to='exam/images/%y%m%d/', blank=True)
    # author
    def get_absolute_url(self):
        return f'/exam/prob/{self.pk}/'

    def __str__(self):
        return f'[{self.num}]{self.name}'

exam/views.py
from django.shortcuts import render
from .models import Student #모델을 가져오고 그 안에 있는 Post클래스 가져오기
from django.views.generic import ListView, DetailView # 장고가 가지고 있는 클래스들 리스트를 볼수 있고 하나하나 볼수있는 페이지
# Create your views here.

#CBV 방식
# class PostList(ListView):
#     model = Student #자동적으로 post_list로 저장 따라서 view파일에 posts를 쓴것을 바꿔줘야함
#     template_name = 'exam/index.html'  #템플릿 지정 (지정안하면 post_list로 자동지정)

def index(request):
    return render(
        request,
        'exam/index.html',
    )
class St_List(ListView):
    model = Student #자동적으로 post_list로 저장 따라서 view파일에 posts를 쓴것을 바꿔줘야함
    template_name = 'exam/st_list.html' #템플릿 지정 (지정안하면 post_list로 자동지정)
    ordering = '-pk' #오름차순, 내림차순 지정

class St_Detail(ListView):
    model = Student #자동적으로 post_list로 저장 따라서 view파일에 posts를 쓴것을 바꿔줘야함
    template_name = 'exam/st_card.html' #템플릿 지정 (지정안하면 post_list로 자동지정)
    ordering = '-pk' #오름차순, 내림차순 지정

#FBV 방식
#def index(request):
#    posts = Post.objects.all().order_by('-pk')#Post.object.all은 데이터 베이스 안에있는 모든것들을 가져오기
                                             #order_by(-pk)는 역순으로 가져오기 -가 안붙으면 순서대로

    #여기서의 posts의미는 모든 게시글을 의미
#    return render(
#        request,
#        'blog/index.html',
#        {#중괄호 안에 의미는 html에 넘겨줄 데이터가 있을때 중괄호 사용
#            'posts': posts,
            #변수  : 데이터 형태를 가짐
#        }
#    )

#class를 이용한 방식
# class PostDetail(DetailView):
#     model = Post
#     template_name = 'blog/single_post_page.html'

#함수를 이용한 방식
# def single_post_page(request, pk):
#     post = Post.objects.get(pk=pk) #pk값은 현재 pk값을 가져와라 라는 의미
#     return render(
#         request,
#         'blog/single_post_page.html',
#         {#html에 post변수를 넘겨준다
#             'post' : post,
#         }
#     )

exam/templates/exam/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>2023_1_Midterm</title>
    <link href="{% static 'exam/bootstrap4/css/midterm.min.css' %}" rel="stylesheet" type="text/css">

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    <div class = "row">
        <div class="col-3">

            <a class="btn btn-outline-primary btn-block" href="/exam" role="button">Exam Home</a>
            <a class="btn btn-outline-info btn-block" href="/exam/prob" role="button">Student List</a>
            {% block menu %}
            <h2>메뉴 테스트</h2>
            {% endblock %}
        </div>

        <div class="col-9">
            {% block main_area %} <!--모듈화 만들기-->
            {% endblock %}

            </div>
        </div>
    </div>
</div>
    <hr>

</body>
</html>

exam/templates/exam/index.html
{% extends 'exam/base.html' %}

            {% block main_area %}
            <div class="media">
                <img src="https://loremflickr.com/200/200" class="mr-3" alt="...">
                <div class="media-body">
                    <h5 class="mt-0">Main Page</h5>
                    <p> home 페이지에 오신 것을 환영합니다. </p>
                    <p>dummy text -
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet, at atque cupiditate delectus dignissimos doloremque et facere illum laudantium mollitia nobis officiis quibusdam quis, repellendus sequi sint, unde voluptatem.
                    </p>
                </div>
            </div>
            {% endblock %}

exam/templates/exam/st_card.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>2023_1_Midterm</title>
    <link href="{% static 'exam/bootstrap4/css/midterm.min.css' %}" rel="stylesheet" type="text/css">

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container">
        <div class = row>
            <div class="col-3">
                <hr>
                <h3> 사용된 링크 버튼</h3>
                <a class="btn btn-outline-primary btn-block" href="/exam" role="button">Exam Home</a>
                <a class="btn btn-outline-info btn-block" href="http://127.0.0.1:8000/exam/prob" role="button">Student List</a>
            </div>
            <div class="col-9">
                <h3> 사용된 학생증 카드 예 </h3>
                <h3> {{ Student.name }}의 ID CARD</h3>
                    <div class="card" style="width: 18rem;">
                        {% if student.image %}
                        <img src="{{ student.image }}" class="card-img-top" alt="...">
                        {% else %}
                            <img src="https://loremflickr.com/300/200" class="card-img-top" alt="...">
                        {% endif %}


                        <div class="card-body">
                            <h5 class="card-title">{{ Student.name }}</h5>
                            <p class="card-text">학번 : {{ Student.num }}</p>
                            <p class="card-text">학과 : {{ Student.depart }}</p>
                            <p class="card-text">생년월일 : {{ Student.birth }}</p>
                        </div>
                    </div>
            </div>

        </div>
    </div>
</body>
</html>

exam/templates/exam/st_list.html
{% extends 'exam/base.html' %}
            {% block menu %}
            {% endblock %}

            {% block main_area %} <!--모듈화-->
            <table class="table table-striped">
                <thead>
                  <tr>
                    <th scope="col">St_ID</th>
                    <th scope="col">NAME</th>
                    <th scope="col">DETAIL</th>
                  </tr>
                </thead>
                <tbody>
                {% for s in student_list %}
                  <tr>
                    <th scope="row">{{ s.num }}</th>
                    <td>{{ s.name }}</td>
                    <td><a class="btn btn-outline-success" href="{{ s.get_absolute_url }}" role="button">학생증 보기</a></td>
                  </tr>
                {% endfor %}
                </tbody>
            </table>
            {% endblock %}