Django_prj/urls.py
#path뒤 include 추가
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),#어드민 사이트 연결해주기 admin을 붙였을때 링크되는 위치
    path('', include('single_pages.urls')), #아무것도 붙이지 않으면 single_pages로(single_pages에 urls파일이 없으므로 생성하기)
    path('blog/', include('blog.urls')),#blog를 붙였을때 연결위치(마찬가지로 blog에도 urls파일 생성해주기)
    path('exam/', include('exam.urls')),
    path('accounts/', include('allauth.urls')),
    path('final4/', include('final4.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
#Django_prj url에서 형식 가져옴
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.PostList.as_view()),#CBV방식의 지정(views에 있는 PostList의 클래스를 보여라 라는뜻)
    #path('', views.index),#FBV방식의 지정
    #CBV방식
    path('<int:pk>/', views.PostDetail.as_view()),
    path('category/<str:slug>/', views.category_page),#문자열을 slug에 담아서
    path('create_post/', views.PostCreate.as_view()), #PostCreate 클래스 참조
    path('update_post/<int:pk>/', views.PostUpdate.as_view()), #postupdate 클래스 참조
    ##댓글 부분
    path('<int:pk>/new_comment/', views.new_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('delete_comment/<int:pk>', views.delete_comment),
    #검색 부분
    path('search/<str:q>/',views.PostSearch.as_view()),
    #FBV방식
    #path('<int:pk>/', views.single_post_page),#모델을 포함시키는 형태로 만들기 위해 single_pages랑 살짝 다름
        #int:pk는 views.single_post_page 여기에 인자값으로 넘김.
]

blog/models.py
import os

from django.db import models
from django.contrib.auth.models import User #장고에서 기본으로 만든 유저 테이블
# Create your models here.

class Tag(models.Model): #Tag db
    name = models.CharField(max_length=50, unique=True)  # unique 겹치지 않게하는것
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)  # 주요단어(타이틀로 쓸 수 있는것),unicode 한글가능

    def __str__(self):
        return self.name
class Category(models.Model): #카테고리 db테이블 만들기
    name = models.CharField(max_length=50, unique=True) #unique 겹치지 않게하는것
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True) #주요단어(타이틀로 쓸 수 있는것),unicode 한글가능

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return f'/blog/category/{self.slug}/'  #f''는 문자열을 만드는 함수 #self.pk는 해당객체의 primary key

    class Meta:
        verbose_name_plural = 'Categories' #어드민 사이트 이름 변경하기

class Post(models.Model): #일종의 db구조 , field설정
    title = models.CharField(max_length=30)
    hook_text = models.CharField(max_length=100, blank=True)#검색어를 넣을 수 있는 필드 blank=true(필수항목x)
    contents = models.TextField()

    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True) #blank=true는 필수 항목이 아니라는것을 의미
    file_upload = models.FileField(upload_to='blog/files/%Y/%m/%d/', blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    #author
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)#models.CASCADE를 하면 포스트도 지워짐

    #1대 다 일때 foreignkey
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)#카테고리 지정하기

    # 다대 다 관계 ManyToManyField
    tags = models.ManyToManyField(Tag, blank=True)  # 카테고리 지정하기

    #{self.pk} : 타이틀의 앞에다가 번호를 붙여줌 프라이머리 키 의미.
    #{self.title} : 내가 설정한 타이틀로 제목을 설정해줌ㅂ

    def __str__(self):
        return f'[{self.pk}]{self.title} :: {self.author}'

    #index.html에 사용되는 함수 (블로그 링크 관력)
    def get_absolute_url(self):
        return f'/blog/{self.pk}/'  #f''는 문자열을 만드는 함수 #self.pk는 해당객체의 primary key

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1] #(test.txt ..ttt.final.real.doc 일 경우 점을 기준해 쪼개라)
                                                   #[-1]이기때문에 마지막 .을 가져와서 리턴하는 함수

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now = True)
    def __str__(self):
        return f'{self.author}::{self.content}'
    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'

blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:             #ModelForm에서 상속받은 경우에 있어야함
        model = Comment
        fields = ('content', )

blog/views.py
from django.shortcuts import render, redirect
from .models import Post,Category,Tag, Comment #모델을 가져오고 그 안에 있는 Post클래스 가져오기
from django.views.generic import ListView, DetailView,CreateView, UpdateView # 장고가 가지고 있는 클래스들 리스트를 볼수 있고 하나하나 볼수있는 페이지
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from .forms import CommentForm
from django.shortcuts import get_object_or_404 #db에서 하나만 가져오는 명령어
from django.db.models import Q
# Create your views here.

#CBV 방식
class PostList(ListView):
    model = Post #자동적으로 post_list로 저장 따라서 view파일에 posts를 쓴것을 바꿔줘야함
    #template_name = 'blog/index.html' #템플릿 지정 (지정안하면 post_list로 자동지정)
    ordering = '-pk' #오름차순, 내림차순 지정

    paginate_by = 2 ##한페이지에 몇개씩 보여줄 건지

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data() #post_list를 가져옴
        context['categories'] = Category.objects.all() #Category db의 내용을 가져옴 #context를 추가 안할시 기본적으로 post_list를 가져옴
        context['no_category_post_count'] = Post.objects.filter(category=None).count()#카테고리가 분류되어있지 않은 경우(미분류 갯수)
        return context # -> post_list.html

#FBV 방식
#def index(request):
#    posts = Post.objects.all().order_by('-pk')#Post.object.all은 데이터 베이스 안에있는 모든것들을 가져오기
                                             #order_by(-pk)는 역순으로 가져오기 -가 안붙으면 순서대로

    #여기서의 posts의미는 모든 게시글을 의미
#    return render(
#        request,
#        'blog/index.html',
#        {#중괄호 안에 의미는 html에 넘겨줄 데이터가 있을때 중괄호 사용
#            'posts': posts,
            #변수  : 데이터 형태를 가짐
#        }
#    )

#class를 이용한 방식
class PostDetail(DetailView):
    model = Post
    # template_name = 'blog/single_post_page.html'
    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data() #post_list를 가져옴
        context['categories'] = Category.objects.all() #Category db의 내용을 가져옴
        context['no_category_post_count'] = Post.objects.filter(category=None).count()#카테고리가 분류되어있지 않은 경우(미분류 갯수)
        context['comment_form'] = CommentForm #form.py에서 만든걸 comment_form변수에 넣음
        return context # -> post_detail.html (post, categories, no_category_post_count)것들이 넘어감

#함수를 이용한 방식
# def single_post_page(request, pk):
#     post = Post.objects.get(pk=pk) #pk값은 현재 pk값을 가져와라 라는 의미
#     return render(
#         request,
#         'blog/single_post_page.html',
#         {#html에 post변수를 넘겨준다
#             'post' : post,
#         }
#     )

def category_page(request, slug): #프로그래밍, 문화-예술, 웹개발, no_category #context는 {중괄호 안에 넣어서 전송}
    if slug == 'no_category':
        category = '미분류'
        post_list = Post.objects.filter(category = None)
    else:
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)

    return render(
        request,
        'blog/post_list.html',
        {  #context 넘겨주기
            'post_list' : post_list,
            'categories' : Category.objects.all(),
            'no_category_post_count' : Post.objects.filter(category=None).count(),
            'category' : category,
        },
    )

#/blog/create_post/
class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView): #createview는 폼을 만드는 놈
    model = Post
    fields = ['title', 'hook_text', 'contents', 'head_image', 'file_upload', 'category', 'tags'] #이미 로그인이 되어있어 user가 빠짐
    #template_name = post_form.html 자동으로 열림

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff #관리자 계정이거나 staff계정이거나 확인

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):#로그인만 되면 되겠금 할려면 뒷부분날리기
            form.instance.author = current_user
            #not tag
            return super(PostCreate, self).form_valid(form)
        else:
            return redirect('/blog/')

#/blog/update_post/pk
class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'hook_text', 'contents', 'head_image', 'file_upload', 'category', 'tags'] #이미 로그인이 되어있어 user가 빠짐
    #기본 템플릿 post_form.html 따라서 생성할때랑 공유하게 됨 따라서 다른 템플릿 사용
    template_name = "blog/post_update_form.html"
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied
def csrf_failure(request, reason=""):
    return redirect('/blog/')

def new_comment(request, pk):  #댓글 쓰기 함수
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)

        if request.method == "POST":
            comment_form = CommentForm(request.POST) #폼 가져오기
            if comment_form.is_valid(): #폼이 정상적이라면
                comment = comment_form.save(commit=False)#commit은 임시저장의 기능
                comment.post = post
                comment.author = request.user #필요한 부분 채우기 날짜, 시간 등등
                comment.save()
                return redirect(comment.get_absolute_url())
        else:
            return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

def delete_comment(request, pk): #댓글 지우기 함수
    comment = get_object_or_404(Comment, pk= pk)
    post = comment.post
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

class CommentUpdate(LoginRequiredMixin,UpdateView): #댓글 수정하기 클래스
    model = Comment
    form_class = CommentForm #별도로 폼을 만들어놔서 자동생성을 안쓰고 만듣어 놓은거 사용
    #comment_form.html을 찾으려고 함
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

#검색 기능 클래스 class PostList(ListView)를 상속 => post_list.html
    #def get_queryset(self):
            #post_list = Post.objects.all  이라는 것이 생략 되어있음 따라서 오버라이딩을 해서 다른걸 동작하게 만듬
class PostSearch(PostList):
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q'] #q = 서치할 단어
        post_list = Post.objects.filter(
            Q(title__contains=q) | Q(tags__name__contains=q)
        ).distinct() #distinct는 중복을 하나로 만드는 것
        return post_list

    def get_context_data(self, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})'

        return context

blog/templates/blog/base.html
{#1.앱 만들기: 가상환경 실행 후 python manage.py startapp blog#}
{##blog = 앱 이름#}
{##}
{#2.모델 만들기: blog/models.py - Post모델 만들기, Django_prj/settings.py - App 추가하기#}
{##모델 변경,추가하면 cmd에 migrate 해주기#}
{##}
{#3.Post 모델 admin에 등록하기: blog/admin.py - from .models import Post, admin.site.register(Post)#}
{##}
{#4. index 페이지 만들기:#}
{#Django_prj/urls.py -> blog/urls.py -> blog/views.py -> blog/templates/blog/index.html#}
{##}
{#5. Post 목록 가져오기: blog/views.py -> blog/templates/blog/index.py#}
{##}
{#6. post_detail 만들기: blog/urls.py -> blog/views.py -> blog/templates/blog/single_post_page.html#}
{##}
{#7. get_absolute_url()으로 고유 url 부여하기: blog/models.py -> blog/templates/blog/post_list.html#}
{##}
{#8. ListView로 포스트목록페이지 만들기: blog/urls.py -> blog/views.py -> post_list.html#}
{#   DetailView로 포스트상세페이지 만들기: blog/views.py -> blog/urls.py#}
{##}
{#9.#}
<!DOCTYPE html>
{% load static %}  <!-- static 폴더를 사용하겠다 -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block head_title %}Blog{% endblock %}</title>
    <link rel= "stylesheet" href = "{% static 'blog/bootstrap4/css/bootstrap.min.css' %}"> <!-- 여기를 참조 고정되서 사용 -->

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/a506b963cb.js" crossorigin="anonymous"></script> <!-- 폰트 -->
</head>
<body>

    {% include 'blog/nav.html' %}

    <div class="container my-4"> <!-- 마진을 의미, 위 아래에 중간 정도의 크기 mt(위), mb(아래), ml(오른쪽), mr(오른쪽) -->
        <!-- mx(수평), my(수직) -->
        <div class = "row">
            <div class = "col-sm-8" id="main-area">
            {% block main_area %}

            {% endblock %}
            </div>

            <!-- Search widget-->
            <div class = "col-sm-4">
                    <div class="card mb-4">
                        <div class="card-header">Search</div>
                        <div class="card-body">
                            <div class="input-group">
                                <input id="search-input" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                                <button class="btn btn-primary" onclick="searchPost();" id="button-search" type="button">Go!</button>
                            </div>
                        </div>
                    </div>
                    <!-- Categories widget-->
                    <div class="card mb-4" id = 'categories-card'>
                        <div class="card-header">Categories</div>
                        <div class="card-body">
                            <div class="row">
                                <!-- post_list(post), categories, no_category_post_count -->

                                    <ul> <!-- categories -->
                                        {% for category in categories %}
                                        <li>
                                            <a href = "{{ category.get_absolute_url }}">
                                                {{ category }} ({{category.post_set.count}})
                                            </a>
                                        </li>
                                        {% endfor %}
                                        <li>
                                            <a href = "/blog/category/no_category/">
                                                미분류 ({{no_category_post_count }})
                                            </a>
                                        </li>
                                    </ul>
                            </div>
                        </div>
                    </div>
            </div>
            </div>
        </div>

    {% include 'blog/footer.html' %}

    <script>
        function searchPost(){
            let searchValue = document.getElementById("search-input").value.trim();
            if(searchValue.length>1){
                location.href = "/blog/search/" + searchValue + "/";
            }
            else{
                alert("검색어(" + searchValue + ")가 너무 짧습니다");
            }
        };
        {#엔터키를 눌러도 검색되게 하기#}
        document.getElementById("search-input").addEventListener("keyup", function(event){
            if(event.key === 'Enter'){
                searchPost();
            }
        });
    </script>

</body>
</html>

blog/templates/blog/base_full_width.html
<!DOCTYPE html>
{% load static %}  <!-- static 폴더를 사용하겠다 -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block head_title %}Blog{% endblock %}</title>
    <link rel= "stylesheet" href = "{% static 'blog/bootstrap4/css/bootstrap.min.css' %}"> <!-- 여기를 참조 고정되서 사용 -->

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/a506b963cb.js" crossorigin="anonymous"></script> <!-- 폰트 -->
</head>
<body>

    {% include 'blog/nav.html' %}

    <div class="container my-4"> <!-- 마진을 의미, 위 아래에 중간 정도의 크기 mt(위), mb(아래), ml(오른쪽), mr(오른쪽) -->
        <!-- mx(수평), my(수직) -->
        <div class = "row">
            <div class = "col-12" id="main-area">
            {% block main_area %}

            {% endblock %}
            </div>
        </div>
    </div>

    {% include 'blog/footer.html' %}

</body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base_full_width.html' %}
{#사이드 위젯이 없는 사이트#}
{% load crispy_forms_tags %}

    {% block head_title %}Edit Comment - Blog{% endblock %}

    {% block main_area %}
        <h1>Edit Comment</h1>
        <hr />
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
            <table>
                {{ form | crispy }}
            </table>
            <button type="submit" class="btn btn_primary float-right">Submit</button>
        </form>
    {% endblock %}

blog/templates/blog/footer.html
    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
    </footer>

blog/templates/blog/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Blog</title>
</head>
<body>
    <h1>Blog</h1>
    <!--파이썬 코드를 html에서 사용할려면 {}사용 posts는 views에서 넘겨준 posts를 사용한것
    {}중괄호 하나는 파이썬코드
    중괄호 두개는 파이썬 변수
    p.title과 p.created_at p.content는 model안에있는 변수들-->
    <h2><a href = "/">HOME</a></h2>
    {% for p in post_list %}
        <hr/>
        <h2>{{ p.title }}</h2>
        <h2><a href="{{ p.get_absolute_url }}">{{ p.title }}</a></h2>
        <h4>{{ p.created_at }}</h4>
        <p>{{ p.contents }}</p>
    {% endfor %}

</body>
</html>

blog/templates/blog/post_detail.html
            {% extends 'blog/base.html' %}
            {% load crispy_forms_tags %}

            {% block head_title %}
                {{ post.title }} - Blog
            {% endblock %}

            {% block main_area %}

                <!-- Post content-->
                <article>
                <div id="post-area">
                    <!-- Post header-->
                    <header class="mb-4">
                        <!-- Post title-->
                        <h1 class="fw-bolder mb-1">{{ post.title }}</h1>
                        <h5 class="text-muted">{{ post.hook_text }}</h5>
                        <!-- Post meta content-->
                        <div class="text-muted fst-italic mb-2">Posted on {{ post.created_at }}
                            by <a href="#">{{ post.author | upper }}</a></div>
                        <!--edit button 수정하기 버튼-->
                        {% if user.is_authenticated and user == post.author %}
                            <a class="btn btn-info btn-sm float-right" href="/blog/update_post/{{ post.pk }}" role="button">
                                <i class="fas fa-pen"></i>Edit Post
                            </a>
                        {% endif %}
                        <!-- Post categories-->
                        {% if post.category %}
                            <span class="badge badge-secondary">{{ post.category}}</span>
                        {% else %}
                            <span class="badge badge-secondary">미분류</span>
                        {% endif %}
                    </header>
                    <!-- Preview image figure-->
                    <figure class="mb-4">
                        {% if post.head_image %}
                            <img class="img-fluid rounded" src="{{ post.head_image.url }}" alt="{{ post.title }} head image" />
                        {% else %}
                            <img class="img-fluid rounded" src="https://picsum.photos/seed/{{post.id}}/800/200" alt="random image" />
                        {% endif %}
                    </figure>
                    <!-- Post content-->
                    <section class="mb-5">
                        <p class="fs-5 mb-4">{{ post.contents | linebreaksbr }}</p><!--엔터기능 줄바꿈-->

                        <!-- tags -->
                        {% if post.tags.exists %}
                            <i class="fas fa-tags"></i>
                            {% for tag in post.tags.all %}
                                <span class = "badge badge-pill badge-light">{{ tag }}</span>
                            {% endfor %}
                            <br /><br />
                        {% endif %}

                        {% if post.file_upload %}
                            <a href="{{ post.file_upload.url }}" class="btn btn-outline-dark" role="button" download>Download:
                            {% if post.get_file_ext == 'csv' %}
                                <i class="fas fa-file-cvs"></i>
                            {% elif post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}
                                <i class="fas fa-file-excel"></i>
                            {% elif post.get_file_ext == 'docx' or post.get_file_ext == 'doc' %}
                                <i class="fas fa-file-word"></i>
                            {% else %}
                                <i class="fas fa-file"></i>
                            {% endif %}
                            {{ post.get_file_name }}
                            </a>
                        {% endif %}
                    </section>
                </div>
                </article>

                <!-- Comments section -->
                <section class="mb-5">
                <div id="comment-area">
                    <!-- Comment form-->
                    <div class="card bg-light">
                        <div class="card-header">Leave a Comment</div>
                        <div class="card-body">
                            {% if user.is_authenticated %}
                            <form class="mb-4" id="comment-form" method="POST"
                                  action="{{ post.get_absolute_url }}new_comment/">
                                {% csrf_token %}
                                <div class="form-group">
                                    {{ comment_form | crispy }}
                                </div>
                                <button type="submit" class="btn btn-primary float-right">submit</button>
                            </form>
                            {% else %}
                            <a role="button" class="btn btn-outline-dark btn-block btn-sm"
                               href="#" data-toggle="modal" data-target="#loginModal">Log In and leave a comment</a>
                            {% endif %}
                        </div>
                    </div>

                    <div class="card">
                        <div class="card-body">

                        {% if post.comment_set.exists %}
                            {% for comment in post.comment_set.iterator %}
                            <!-- Single comment-->
                            <div class="d-flex mb-4">
                                <div class="flex-shrink-0">
                                    <img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg&text={{ comment.author }}" alt="..." />
                                </div>
                                <div class="ms-3">
                                    {#  수정하기 버튼 만들기#}
                                    {% if user.is_authenticated and comment.author == user %}
                                    <div class="float-right">
                                    <a role="button" class = "btn btn-sm btn-info"
                                       id = "comment-{{ comment.pk }}-update-btn"
                                       href="/blog/update_comment/{{ comment.pk }}/">
                                        <small>edit</small>
                                    </a>
                                    <a role="button" class ="btn btn-sm btn-danger"
                                       id = "comment-{{ comment.pk }}=delete-modal-btn"
                                       href="/blog/delete_comment/{{ comment.pk }}">
                                        <small>delete</small>
                                    </a>
                                    </div>
                                    {% endif %}
                                    <div class="fw-bold">{{ comment.author }}&nbsp;&nbsp;
                                        <small class="text-muted">{{ comment.created_at }}</small> </div>
                                    <div>{{ comment.content | linebreaks }}</div>
                                    {% if comment.created_at != comment.modified_at %}
                                        <p class="text-muted float-right"><small>Updated: {{ comment.modified_at }}</small></p>
                                    {% endif %}
                                </div>
                            </div>
                            {% endfor %}
                        {% endif %}

                        </div>
                    </div>
                </div>
                </section>
            {% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base_full_width.html' %}
{#사이드 위젯이 없는 사이트#}
{% load crispy_forms_tags %}

    {% block head_title %}Create Post - Blog{% endblock %}

    {% block main_area %}
        <h1>Create New Post</h1>
        <hr />
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
            <table>
                {{ form | crispy }}
            </table>
            <button type="submit" class="btn btn_primary float-right">Submit</button>
        </form>
    {% endblock %}

blog/templates/blog/post_update_form.html
{% extends 'blog/base_full_width.html' %}
{#사이드 위젯이 없는 사이트#}
{% load crispy_forms_tags %}
    {% block head_title %}
       Edit Post - Blog
    {% endblock %}

    {% block main_area %}
        <h1>Edit Post</h1>
        <hr />
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
            <table>
                {{ form | crispy }}
            </table>
            <button type="submit" class="btn btn_primary float-right">Submit</button>
        </form>
    {% endblock %}